# Macros
DEPS = -lpthread -lrt -std=c99

Part1: Part1.c
	gcc $(DEPS) Part1.c -c
	gcc $(DEPS) Part1.o -o part1
	rm Part1.o
  
Part2: Part2.c
	gcc $(DEPS) Part2.c -c
	gcc $(DEPS) Part2.o -o part2
	rm Part2.o